//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zmtapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodData
    {
        public int id { get; set; }
        public string rname { get; set; }
        public string imgdata { get; set; }
        public string address { get; set; }
        public string delimg { get; set; }
        public string somedata { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> rating { get; set; }
        public string arrimg { get; set; }
    }
}
